/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LocaleWizardRouteImport } from './routes/$locale/wizard'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleTalkRouteImport } from './routes/$locale/talk'
import { Route as LocaleSignupRouteImport } from './routes/$locale/signup'
import { Route as LocaleShoppingListRouteImport } from './routes/$locale/shopping-list'
import { Route as LocaleSettingsRouteImport } from './routes/$locale/settings'
import { Route as LocaleProjectsRouteImport } from './routes/$locale/projects'
import { Route as LocaleProjectRouteImport } from './routes/$locale/project'
import { Route as LocaleProfileRouteImport } from './routes/$locale/profile'
import { Route as LocaleProductsRouteImport } from './routes/$locale/products'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleOrdersRouteImport } from './routes/$locale/orders'
import { Route as LocaleNewRouteImport } from './routes/$locale/new'
import { Route as LocaleMachineBuilderRouteImport } from './routes/$locale/machine-builder'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleGuiderRouteImport } from './routes/$locale/guider'
import { Route as LocaleConvertRouteImport } from './routes/$locale/convert'
import { Route as LocaleConfigureRouteImport } from './routes/$locale/configure'
import { Route as LocaleConfiguratorRouteImport } from './routes/$locale/configurator'
import { Route as LocaleComponentsRouteImport } from './routes/$locale/components'
import { Route as LocaleCompareRouteImport } from './routes/$locale/compare'
import { Route as LocaleClaimsRouteImport } from './routes/$locale/claims'
import { Route as LocaleChatRouteImport } from './routes/$locale/chat'
import { Route as LocaleAssembliesRouteImport } from './routes/$locale/assemblies'
import { Route as LocaleAppRouteImport } from './routes/$locale/app'
import { Route as LocaleAdvisorRouteImport } from './routes/$locale/advisor'
import { Route as LocaleAdminRouteImport } from './routes/$locale/admin'
import { Route as LocaleGuiderIndexRouteImport } from './routes/$locale/guider.index'
import { Route as LocaleConfiguratorIndexRouteImport } from './routes/$locale/configurator.index'
import { Route as LocaleRfqRfqIdRouteImport } from './routes/$locale/rfq.$rfqId'
import { Route as LocaleProductSkuRouteImport } from './routes/$locale/product.$sku'
import { Route as LocaleOffertRfqIdRouteImport } from './routes/$locale/offert.$rfqId'
import { Route as LocaleOcOrderIdRouteImport } from './routes/$locale/oc.$orderId'
import { Route as LocaleGuiderSlugRouteImport } from './routes/$locale/guider.$slug'
import { Route as LocaleConfiguratorFamilyRouteImport } from './routes/$locale/configurator.$family'
import { Route as LocaleBomBomIdRouteImport } from './routes/$locale/bom.$bomId'
import { Route as LocaleAssemblySlugRouteImport } from './routes/$locale/assembly.$slug'
import { Route as LocaleAdminSettingsRouteImport } from './routes/$locale/admin.settings'
import { Route as LocaleAdminRfqRouteImport } from './routes/$locale/admin.rfq'
import { Route as LocaleAdminProductsRouteImport } from './routes/$locale/admin.products'
import { Route as LocaleAdminPricingRouteImport } from './routes/$locale/admin.pricing'
import { Route as LocaleAdminOrdersRouteImport } from './routes/$locale/admin.orders'
import { Route as LocaleAdminKnowledgeRouteImport } from './routes/$locale/admin.knowledge'
import { Route as LocaleAdminIntegrationsRouteImport } from './routes/$locale/admin.integrations'
import { Route as LocaleAdminImportRouteImport } from './routes/$locale/admin.import'
import { Route as LocaleAdminImagesRouteImport } from './routes/$locale/admin.images'
import { Route as LocaleAdminEkonomiRouteImport } from './routes/$locale/admin.ekonomi'
import { Route as LocaleAdminDashboardRouteImport } from './routes/$locale/admin.dashboard'
import { Route as LocaleAdminCrmRouteImport } from './routes/$locale/admin.crm'
import { Route as LocaleAdminClaimsRouteImport } from './routes/$locale/admin.claims'
import { Route as LocaleAdminAuditRouteImport } from './routes/$locale/admin.audit'
import { Route as ApiPublicNotifyRfqRouteImport } from './routes/api/public/notify/rfq'
import { Route as LocaleConfiguratorSchemaSchemaIdRouteImport } from './routes/$locale/configurator.schema.$schemaId'
import { Route as LocaleAdminOrderbekraftelseOrderIdRouteImport } from './routes/$locale/admin.orderbekraftelse.$orderId'
import { Route as LocaleAdminOffertRfqIdRouteImport } from './routes/$locale/admin.offert.$rfqId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWizardRoute = LocaleWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTalkRoute = LocaleTalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignupRoute = LocaleSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleShoppingListRoute = LocaleShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSettingsRoute = LocaleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsRoute = LocaleProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectRoute = LocaleProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProfileRoute = LocaleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsRoute = LocaleProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOrdersRoute = LocaleOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleNewRoute = LocaleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMachineBuilderRoute = LocaleMachineBuilderRouteImport.update({
  id: '/machine-builder',
  path: '/machine-builder',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuiderRoute = LocaleGuiderRouteImport.update({
  id: '/guider',
  path: '/guider',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleConvertRoute = LocaleConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleConfigureRoute = LocaleConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleConfiguratorRoute = LocaleConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleComponentsRoute = LocaleComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCompareRoute = LocaleCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleClaimsRoute = LocaleClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChatRoute = LocaleChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAssembliesRoute = LocaleAssembliesRouteImport.update({
  id: '/assemblies',
  path: '/assemblies',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdvisorRoute = LocaleAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuiderIndexRoute = LocaleGuiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleGuiderRoute,
} as any)
const LocaleConfiguratorIndexRoute = LocaleConfiguratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleConfiguratorRoute,
} as any)
const LocaleRfqRfqIdRoute = LocaleRfqRfqIdRouteImport.update({
  id: '/rfq/$rfqId',
  path: '/rfq/$rfqId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductSkuRoute = LocaleProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOffertRfqIdRoute = LocaleOffertRfqIdRouteImport.update({
  id: '/offert/$rfqId',
  path: '/offert/$rfqId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOcOrderIdRoute = LocaleOcOrderIdRouteImport.update({
  id: '/oc/$orderId',
  path: '/oc/$orderId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuiderSlugRoute = LocaleGuiderSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleGuiderRoute,
} as any)
const LocaleConfiguratorFamilyRoute =
  LocaleConfiguratorFamilyRouteImport.update({
    id: '/$family',
    path: '/$family',
    getParentRoute: () => LocaleConfiguratorRoute,
  } as any)
const LocaleBomBomIdRoute = LocaleBomBomIdRouteImport.update({
  id: '/bom/$bomId',
  path: '/bom/$bomId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAssemblySlugRoute = LocaleAssemblySlugRouteImport.update({
  id: '/assembly/$slug',
  path: '/assembly/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminSettingsRoute = LocaleAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminRfqRoute = LocaleAdminRfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminProductsRoute = LocaleAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminPricingRoute = LocaleAdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminOrdersRoute = LocaleAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminKnowledgeRoute = LocaleAdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminIntegrationsRoute = LocaleAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminImportRoute = LocaleAdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminImagesRoute = LocaleAdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminEkonomiRoute = LocaleAdminEkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminDashboardRoute = LocaleAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminCrmRoute = LocaleAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminClaimsRoute = LocaleAdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminAuditRoute = LocaleAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const ApiPublicNotifyRfqRoute = ApiPublicNotifyRfqRouteImport.update({
  id: '/api/public/notify/rfq',
  path: '/api/public/notify/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleConfiguratorSchemaSchemaIdRoute =
  LocaleConfiguratorSchemaSchemaIdRouteImport.update({
    id: '/schema/$schemaId',
    path: '/schema/$schemaId',
    getParentRoute: () => LocaleConfiguratorRoute,
  } as any)
const LocaleAdminOrderbekraftelseOrderIdRoute =
  LocaleAdminOrderbekraftelseOrderIdRouteImport.update({
    id: '/orderbekraftelse/$orderId',
    path: '/orderbekraftelse/$orderId',
    getParentRoute: () => LocaleAdminRoute,
  } as any)
const LocaleAdminOffertRfqIdRoute = LocaleAdminOffertRfqIdRouteImport.update({
  id: '/offert/$rfqId',
  path: '/offert/$rfqId',
  getParentRoute: () => LocaleAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/advisor': typeof LocaleAdvisorRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/assemblies': typeof LocaleAssembliesRoute
  '/$locale/chat': typeof LocaleChatRoute
  '/$locale/claims': typeof LocaleClaimsRoute
  '/$locale/compare': typeof LocaleCompareRoute
  '/$locale/components': typeof LocaleComponentsRoute
  '/$locale/configurator': typeof LocaleConfiguratorRouteWithChildren
  '/$locale/configure': typeof LocaleConfigureRoute
  '/$locale/convert': typeof LocaleConvertRoute
  '/$locale/guider': typeof LocaleGuiderRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/machine-builder': typeof LocaleMachineBuilderRoute
  '/$locale/new': typeof LocaleNewRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/products': typeof LocaleProductsRoute
  '/$locale/profile': typeof LocaleProfileRoute
  '/$locale/project': typeof LocaleProjectRoute
  '/$locale/projects': typeof LocaleProjectsRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/shopping-list': typeof LocaleShoppingListRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/talk': typeof LocaleTalkRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/wizard': typeof LocaleWizardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/audit': typeof LocaleAdminAuditRoute
  '/$locale/admin/claims': typeof LocaleAdminClaimsRoute
  '/$locale/admin/crm': typeof LocaleAdminCrmRoute
  '/$locale/admin/dashboard': typeof LocaleAdminDashboardRoute
  '/$locale/admin/ekonomi': typeof LocaleAdminEkonomiRoute
  '/$locale/admin/images': typeof LocaleAdminImagesRoute
  '/$locale/admin/import': typeof LocaleAdminImportRoute
  '/$locale/admin/integrations': typeof LocaleAdminIntegrationsRoute
  '/$locale/admin/knowledge': typeof LocaleAdminKnowledgeRoute
  '/$locale/admin/orders': typeof LocaleAdminOrdersRoute
  '/$locale/admin/pricing': typeof LocaleAdminPricingRoute
  '/$locale/admin/products': typeof LocaleAdminProductsRoute
  '/$locale/admin/rfq': typeof LocaleAdminRfqRoute
  '/$locale/admin/settings': typeof LocaleAdminSettingsRoute
  '/$locale/assembly/$slug': typeof LocaleAssemblySlugRoute
  '/$locale/bom/$bomId': typeof LocaleBomBomIdRoute
  '/$locale/configurator/$family': typeof LocaleConfiguratorFamilyRoute
  '/$locale/guider/$slug': typeof LocaleGuiderSlugRoute
  '/$locale/oc/$orderId': typeof LocaleOcOrderIdRoute
  '/$locale/offert/$rfqId': typeof LocaleOffertRfqIdRoute
  '/$locale/product/$sku': typeof LocaleProductSkuRoute
  '/$locale/rfq/$rfqId': typeof LocaleRfqRfqIdRoute
  '/$locale/configurator/': typeof LocaleConfiguratorIndexRoute
  '/$locale/guider/': typeof LocaleGuiderIndexRoute
  '/$locale/admin/offert/$rfqId': typeof LocaleAdminOffertRfqIdRoute
  '/$locale/admin/orderbekraftelse/$orderId': typeof LocaleAdminOrderbekraftelseOrderIdRoute
  '/$locale/configurator/schema/$schemaId': typeof LocaleConfiguratorSchemaSchemaIdRoute
  '/api/public/notify/rfq': typeof ApiPublicNotifyRfqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/advisor': typeof LocaleAdvisorRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/assemblies': typeof LocaleAssembliesRoute
  '/$locale/chat': typeof LocaleChatRoute
  '/$locale/claims': typeof LocaleClaimsRoute
  '/$locale/compare': typeof LocaleCompareRoute
  '/$locale/components': typeof LocaleComponentsRoute
  '/$locale/configure': typeof LocaleConfigureRoute
  '/$locale/convert': typeof LocaleConvertRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/machine-builder': typeof LocaleMachineBuilderRoute
  '/$locale/new': typeof LocaleNewRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/products': typeof LocaleProductsRoute
  '/$locale/profile': typeof LocaleProfileRoute
  '/$locale/project': typeof LocaleProjectRoute
  '/$locale/projects': typeof LocaleProjectsRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/shopping-list': typeof LocaleShoppingListRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/talk': typeof LocaleTalkRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/wizard': typeof LocaleWizardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/audit': typeof LocaleAdminAuditRoute
  '/$locale/admin/claims': typeof LocaleAdminClaimsRoute
  '/$locale/admin/crm': typeof LocaleAdminCrmRoute
  '/$locale/admin/dashboard': typeof LocaleAdminDashboardRoute
  '/$locale/admin/ekonomi': typeof LocaleAdminEkonomiRoute
  '/$locale/admin/images': typeof LocaleAdminImagesRoute
  '/$locale/admin/import': typeof LocaleAdminImportRoute
  '/$locale/admin/integrations': typeof LocaleAdminIntegrationsRoute
  '/$locale/admin/knowledge': typeof LocaleAdminKnowledgeRoute
  '/$locale/admin/orders': typeof LocaleAdminOrdersRoute
  '/$locale/admin/pricing': typeof LocaleAdminPricingRoute
  '/$locale/admin/products': typeof LocaleAdminProductsRoute
  '/$locale/admin/rfq': typeof LocaleAdminRfqRoute
  '/$locale/admin/settings': typeof LocaleAdminSettingsRoute
  '/$locale/assembly/$slug': typeof LocaleAssemblySlugRoute
  '/$locale/bom/$bomId': typeof LocaleBomBomIdRoute
  '/$locale/configurator/$family': typeof LocaleConfiguratorFamilyRoute
  '/$locale/guider/$slug': typeof LocaleGuiderSlugRoute
  '/$locale/oc/$orderId': typeof LocaleOcOrderIdRoute
  '/$locale/offert/$rfqId': typeof LocaleOffertRfqIdRoute
  '/$locale/product/$sku': typeof LocaleProductSkuRoute
  '/$locale/rfq/$rfqId': typeof LocaleRfqRfqIdRoute
  '/$locale/configurator': typeof LocaleConfiguratorIndexRoute
  '/$locale/guider': typeof LocaleGuiderIndexRoute
  '/$locale/admin/offert/$rfqId': typeof LocaleAdminOffertRfqIdRoute
  '/$locale/admin/orderbekraftelse/$orderId': typeof LocaleAdminOrderbekraftelseOrderIdRoute
  '/$locale/configurator/schema/$schemaId': typeof LocaleConfiguratorSchemaSchemaIdRoute
  '/api/public/notify/rfq': typeof ApiPublicNotifyRfqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/advisor': typeof LocaleAdvisorRoute
  '/$locale/app': typeof LocaleAppRoute
  '/$locale/assemblies': typeof LocaleAssembliesRoute
  '/$locale/chat': typeof LocaleChatRoute
  '/$locale/claims': typeof LocaleClaimsRoute
  '/$locale/compare': typeof LocaleCompareRoute
  '/$locale/components': typeof LocaleComponentsRoute
  '/$locale/configurator': typeof LocaleConfiguratorRouteWithChildren
  '/$locale/configure': typeof LocaleConfigureRoute
  '/$locale/convert': typeof LocaleConvertRoute
  '/$locale/guider': typeof LocaleGuiderRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/machine-builder': typeof LocaleMachineBuilderRoute
  '/$locale/new': typeof LocaleNewRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/products': typeof LocaleProductsRoute
  '/$locale/profile': typeof LocaleProfileRoute
  '/$locale/project': typeof LocaleProjectRoute
  '/$locale/projects': typeof LocaleProjectsRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/shopping-list': typeof LocaleShoppingListRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/$locale/talk': typeof LocaleTalkRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/wizard': typeof LocaleWizardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/audit': typeof LocaleAdminAuditRoute
  '/$locale/admin/claims': typeof LocaleAdminClaimsRoute
  '/$locale/admin/crm': typeof LocaleAdminCrmRoute
  '/$locale/admin/dashboard': typeof LocaleAdminDashboardRoute
  '/$locale/admin/ekonomi': typeof LocaleAdminEkonomiRoute
  '/$locale/admin/images': typeof LocaleAdminImagesRoute
  '/$locale/admin/import': typeof LocaleAdminImportRoute
  '/$locale/admin/integrations': typeof LocaleAdminIntegrationsRoute
  '/$locale/admin/knowledge': typeof LocaleAdminKnowledgeRoute
  '/$locale/admin/orders': typeof LocaleAdminOrdersRoute
  '/$locale/admin/pricing': typeof LocaleAdminPricingRoute
  '/$locale/admin/products': typeof LocaleAdminProductsRoute
  '/$locale/admin/rfq': typeof LocaleAdminRfqRoute
  '/$locale/admin/settings': typeof LocaleAdminSettingsRoute
  '/$locale/assembly/$slug': typeof LocaleAssemblySlugRoute
  '/$locale/bom/$bomId': typeof LocaleBomBomIdRoute
  '/$locale/configurator/$family': typeof LocaleConfiguratorFamilyRoute
  '/$locale/guider/$slug': typeof LocaleGuiderSlugRoute
  '/$locale/oc/$orderId': typeof LocaleOcOrderIdRoute
  '/$locale/offert/$rfqId': typeof LocaleOffertRfqIdRoute
  '/$locale/product/$sku': typeof LocaleProductSkuRoute
  '/$locale/rfq/$rfqId': typeof LocaleRfqRfqIdRoute
  '/$locale/configurator/': typeof LocaleConfiguratorIndexRoute
  '/$locale/guider/': typeof LocaleGuiderIndexRoute
  '/$locale/admin/offert/$rfqId': typeof LocaleAdminOffertRfqIdRoute
  '/$locale/admin/orderbekraftelse/$orderId': typeof LocaleAdminOrderbekraftelseOrderIdRoute
  '/$locale/configurator/schema/$schemaId': typeof LocaleConfiguratorSchemaSchemaIdRoute
  '/api/public/notify/rfq': typeof ApiPublicNotifyRfqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/sitemap.xml'
    | '/$locale/admin'
    | '/$locale/advisor'
    | '/$locale/app'
    | '/$locale/assemblies'
    | '/$locale/chat'
    | '/$locale/claims'
    | '/$locale/compare'
    | '/$locale/components'
    | '/$locale/configurator'
    | '/$locale/configure'
    | '/$locale/convert'
    | '/$locale/guider'
    | '/$locale/login'
    | '/$locale/machine-builder'
    | '/$locale/new'
    | '/$locale/orders'
    | '/$locale/privacy'
    | '/$locale/products'
    | '/$locale/profile'
    | '/$locale/project'
    | '/$locale/projects'
    | '/$locale/settings'
    | '/$locale/shopping-list'
    | '/$locale/signup'
    | '/$locale/talk'
    | '/$locale/terms'
    | '/$locale/wizard'
    | '/auth/callback'
    | '/$locale/'
    | '/$locale/admin/audit'
    | '/$locale/admin/claims'
    | '/$locale/admin/crm'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/ekonomi'
    | '/$locale/admin/images'
    | '/$locale/admin/import'
    | '/$locale/admin/integrations'
    | '/$locale/admin/knowledge'
    | '/$locale/admin/orders'
    | '/$locale/admin/pricing'
    | '/$locale/admin/products'
    | '/$locale/admin/rfq'
    | '/$locale/admin/settings'
    | '/$locale/assembly/$slug'
    | '/$locale/bom/$bomId'
    | '/$locale/configurator/$family'
    | '/$locale/guider/$slug'
    | '/$locale/oc/$orderId'
    | '/$locale/offert/$rfqId'
    | '/$locale/product/$sku'
    | '/$locale/rfq/$rfqId'
    | '/$locale/configurator/'
    | '/$locale/guider/'
    | '/$locale/admin/offert/$rfqId'
    | '/$locale/admin/orderbekraftelse/$orderId'
    | '/$locale/configurator/schema/$schemaId'
    | '/api/public/notify/rfq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$locale/admin'
    | '/$locale/advisor'
    | '/$locale/app'
    | '/$locale/assemblies'
    | '/$locale/chat'
    | '/$locale/claims'
    | '/$locale/compare'
    | '/$locale/components'
    | '/$locale/configure'
    | '/$locale/convert'
    | '/$locale/login'
    | '/$locale/machine-builder'
    | '/$locale/new'
    | '/$locale/orders'
    | '/$locale/privacy'
    | '/$locale/products'
    | '/$locale/profile'
    | '/$locale/project'
    | '/$locale/projects'
    | '/$locale/settings'
    | '/$locale/shopping-list'
    | '/$locale/signup'
    | '/$locale/talk'
    | '/$locale/terms'
    | '/$locale/wizard'
    | '/auth/callback'
    | '/$locale'
    | '/$locale/admin/audit'
    | '/$locale/admin/claims'
    | '/$locale/admin/crm'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/ekonomi'
    | '/$locale/admin/images'
    | '/$locale/admin/import'
    | '/$locale/admin/integrations'
    | '/$locale/admin/knowledge'
    | '/$locale/admin/orders'
    | '/$locale/admin/pricing'
    | '/$locale/admin/products'
    | '/$locale/admin/rfq'
    | '/$locale/admin/settings'
    | '/$locale/assembly/$slug'
    | '/$locale/bom/$bomId'
    | '/$locale/configurator/$family'
    | '/$locale/guider/$slug'
    | '/$locale/oc/$orderId'
    | '/$locale/offert/$rfqId'
    | '/$locale/product/$sku'
    | '/$locale/rfq/$rfqId'
    | '/$locale/configurator'
    | '/$locale/guider'
    | '/$locale/admin/offert/$rfqId'
    | '/$locale/admin/orderbekraftelse/$orderId'
    | '/$locale/configurator/schema/$schemaId'
    | '/api/public/notify/rfq'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/sitemap.xml'
    | '/$locale/admin'
    | '/$locale/advisor'
    | '/$locale/app'
    | '/$locale/assemblies'
    | '/$locale/chat'
    | '/$locale/claims'
    | '/$locale/compare'
    | '/$locale/components'
    | '/$locale/configurator'
    | '/$locale/configure'
    | '/$locale/convert'
    | '/$locale/guider'
    | '/$locale/login'
    | '/$locale/machine-builder'
    | '/$locale/new'
    | '/$locale/orders'
    | '/$locale/privacy'
    | '/$locale/products'
    | '/$locale/profile'
    | '/$locale/project'
    | '/$locale/projects'
    | '/$locale/settings'
    | '/$locale/shopping-list'
    | '/$locale/signup'
    | '/$locale/talk'
    | '/$locale/terms'
    | '/$locale/wizard'
    | '/auth/callback'
    | '/$locale/'
    | '/$locale/admin/audit'
    | '/$locale/admin/claims'
    | '/$locale/admin/crm'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/ekonomi'
    | '/$locale/admin/images'
    | '/$locale/admin/import'
    | '/$locale/admin/integrations'
    | '/$locale/admin/knowledge'
    | '/$locale/admin/orders'
    | '/$locale/admin/pricing'
    | '/$locale/admin/products'
    | '/$locale/admin/rfq'
    | '/$locale/admin/settings'
    | '/$locale/assembly/$slug'
    | '/$locale/bom/$bomId'
    | '/$locale/configurator/$family'
    | '/$locale/guider/$slug'
    | '/$locale/oc/$orderId'
    | '/$locale/offert/$rfqId'
    | '/$locale/product/$sku'
    | '/$locale/rfq/$rfqId'
    | '/$locale/configurator/'
    | '/$locale/guider/'
    | '/$locale/admin/offert/$rfqId'
    | '/$locale/admin/orderbekraftelse/$orderId'
    | '/$locale/configurator/schema/$schemaId'
    | '/api/public/notify/rfq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicNotifyRfqRoute: typeof ApiPublicNotifyRfqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/wizard': {
      id: '/$locale/wizard'
      path: '/wizard'
      fullPath: '/$locale/wizard'
      preLoaderRoute: typeof LocaleWizardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/talk': {
      id: '/$locale/talk'
      path: '/talk'
      fullPath: '/$locale/talk'
      preLoaderRoute: typeof LocaleTalkRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/signup': {
      id: '/$locale/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleSignupRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/shopping-list': {
      id: '/$locale/shopping-list'
      path: '/shopping-list'
      fullPath: '/$locale/shopping-list'
      preLoaderRoute: typeof LocaleShoppingListRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/settings': {
      id: '/$locale/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleSettingsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects': {
      id: '/$locale/projects'
      path: '/projects'
      fullPath: '/$locale/projects'
      preLoaderRoute: typeof LocaleProjectsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/project': {
      id: '/$locale/project'
      path: '/project'
      fullPath: '/$locale/project'
      preLoaderRoute: typeof LocaleProjectRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/profile': {
      id: '/$locale/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleProfileRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products': {
      id: '/$locale/products'
      path: '/products'
      fullPath: '/$locale/products'
      preLoaderRoute: typeof LocaleProductsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/orders': {
      id: '/$locale/orders'
      path: '/orders'
      fullPath: '/$locale/orders'
      preLoaderRoute: typeof LocaleOrdersRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/new': {
      id: '/$locale/new'
      path: '/new'
      fullPath: '/$locale/new'
      preLoaderRoute: typeof LocaleNewRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/machine-builder': {
      id: '/$locale/machine-builder'
      path: '/machine-builder'
      fullPath: '/$locale/machine-builder'
      preLoaderRoute: typeof LocaleMachineBuilderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guider': {
      id: '/$locale/guider'
      path: '/guider'
      fullPath: '/$locale/guider'
      preLoaderRoute: typeof LocaleGuiderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/convert': {
      id: '/$locale/convert'
      path: '/convert'
      fullPath: '/$locale/convert'
      preLoaderRoute: typeof LocaleConvertRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/configure': {
      id: '/$locale/configure'
      path: '/configure'
      fullPath: '/$locale/configure'
      preLoaderRoute: typeof LocaleConfigureRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/configurator': {
      id: '/$locale/configurator'
      path: '/configurator'
      fullPath: '/$locale/configurator'
      preLoaderRoute: typeof LocaleConfiguratorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/components': {
      id: '/$locale/components'
      path: '/components'
      fullPath: '/$locale/components'
      preLoaderRoute: typeof LocaleComponentsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/compare': {
      id: '/$locale/compare'
      path: '/compare'
      fullPath: '/$locale/compare'
      preLoaderRoute: typeof LocaleCompareRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/claims': {
      id: '/$locale/claims'
      path: '/claims'
      fullPath: '/$locale/claims'
      preLoaderRoute: typeof LocaleClaimsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/chat': {
      id: '/$locale/chat'
      path: '/chat'
      fullPath: '/$locale/chat'
      preLoaderRoute: typeof LocaleChatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/assemblies': {
      id: '/$locale/assemblies'
      path: '/assemblies'
      fullPath: '/$locale/assemblies'
      preLoaderRoute: typeof LocaleAssembliesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app': {
      id: '/$locale/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/advisor': {
      id: '/$locale/advisor'
      path: '/advisor'
      fullPath: '/$locale/advisor'
      preLoaderRoute: typeof LocaleAdvisorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guider/': {
      id: '/$locale/guider/'
      path: '/'
      fullPath: '/$locale/guider/'
      preLoaderRoute: typeof LocaleGuiderIndexRouteImport
      parentRoute: typeof LocaleGuiderRoute
    }
    '/$locale/configurator/': {
      id: '/$locale/configurator/'
      path: '/'
      fullPath: '/$locale/configurator/'
      preLoaderRoute: typeof LocaleConfiguratorIndexRouteImport
      parentRoute: typeof LocaleConfiguratorRoute
    }
    '/$locale/rfq/$rfqId': {
      id: '/$locale/rfq/$rfqId'
      path: '/rfq/$rfqId'
      fullPath: '/$locale/rfq/$rfqId'
      preLoaderRoute: typeof LocaleRfqRfqIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/product/$sku': {
      id: '/$locale/product/$sku'
      path: '/product/$sku'
      fullPath: '/$locale/product/$sku'
      preLoaderRoute: typeof LocaleProductSkuRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/offert/$rfqId': {
      id: '/$locale/offert/$rfqId'
      path: '/offert/$rfqId'
      fullPath: '/$locale/offert/$rfqId'
      preLoaderRoute: typeof LocaleOffertRfqIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/oc/$orderId': {
      id: '/$locale/oc/$orderId'
      path: '/oc/$orderId'
      fullPath: '/$locale/oc/$orderId'
      preLoaderRoute: typeof LocaleOcOrderIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guider/$slug': {
      id: '/$locale/guider/$slug'
      path: '/$slug'
      fullPath: '/$locale/guider/$slug'
      preLoaderRoute: typeof LocaleGuiderSlugRouteImport
      parentRoute: typeof LocaleGuiderRoute
    }
    '/$locale/configurator/$family': {
      id: '/$locale/configurator/$family'
      path: '/$family'
      fullPath: '/$locale/configurator/$family'
      preLoaderRoute: typeof LocaleConfiguratorFamilyRouteImport
      parentRoute: typeof LocaleConfiguratorRoute
    }
    '/$locale/bom/$bomId': {
      id: '/$locale/bom/$bomId'
      path: '/bom/$bomId'
      fullPath: '/$locale/bom/$bomId'
      preLoaderRoute: typeof LocaleBomBomIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/assembly/$slug': {
      id: '/$locale/assembly/$slug'
      path: '/assembly/$slug'
      fullPath: '/$locale/assembly/$slug'
      preLoaderRoute: typeof LocaleAssemblySlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/settings': {
      id: '/$locale/admin/settings'
      path: '/settings'
      fullPath: '/$locale/admin/settings'
      preLoaderRoute: typeof LocaleAdminSettingsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/rfq': {
      id: '/$locale/admin/rfq'
      path: '/rfq'
      fullPath: '/$locale/admin/rfq'
      preLoaderRoute: typeof LocaleAdminRfqRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/products': {
      id: '/$locale/admin/products'
      path: '/products'
      fullPath: '/$locale/admin/products'
      preLoaderRoute: typeof LocaleAdminProductsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/pricing': {
      id: '/$locale/admin/pricing'
      path: '/pricing'
      fullPath: '/$locale/admin/pricing'
      preLoaderRoute: typeof LocaleAdminPricingRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/orders': {
      id: '/$locale/admin/orders'
      path: '/orders'
      fullPath: '/$locale/admin/orders'
      preLoaderRoute: typeof LocaleAdminOrdersRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/knowledge': {
      id: '/$locale/admin/knowledge'
      path: '/knowledge'
      fullPath: '/$locale/admin/knowledge'
      preLoaderRoute: typeof LocaleAdminKnowledgeRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/integrations': {
      id: '/$locale/admin/integrations'
      path: '/integrations'
      fullPath: '/$locale/admin/integrations'
      preLoaderRoute: typeof LocaleAdminIntegrationsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/import': {
      id: '/$locale/admin/import'
      path: '/import'
      fullPath: '/$locale/admin/import'
      preLoaderRoute: typeof LocaleAdminImportRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/images': {
      id: '/$locale/admin/images'
      path: '/images'
      fullPath: '/$locale/admin/images'
      preLoaderRoute: typeof LocaleAdminImagesRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/ekonomi': {
      id: '/$locale/admin/ekonomi'
      path: '/ekonomi'
      fullPath: '/$locale/admin/ekonomi'
      preLoaderRoute: typeof LocaleAdminEkonomiRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/dashboard': {
      id: '/$locale/admin/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/admin/dashboard'
      preLoaderRoute: typeof LocaleAdminDashboardRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/crm': {
      id: '/$locale/admin/crm'
      path: '/crm'
      fullPath: '/$locale/admin/crm'
      preLoaderRoute: typeof LocaleAdminCrmRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/claims': {
      id: '/$locale/admin/claims'
      path: '/claims'
      fullPath: '/$locale/admin/claims'
      preLoaderRoute: typeof LocaleAdminClaimsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/audit': {
      id: '/$locale/admin/audit'
      path: '/audit'
      fullPath: '/$locale/admin/audit'
      preLoaderRoute: typeof LocaleAdminAuditRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/api/public/notify/rfq': {
      id: '/api/public/notify/rfq'
      path: '/api/public/notify/rfq'
      fullPath: '/api/public/notify/rfq'
      preLoaderRoute: typeof ApiPublicNotifyRfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/configurator/schema/$schemaId': {
      id: '/$locale/configurator/schema/$schemaId'
      path: '/schema/$schemaId'
      fullPath: '/$locale/configurator/schema/$schemaId'
      preLoaderRoute: typeof LocaleConfiguratorSchemaSchemaIdRouteImport
      parentRoute: typeof LocaleConfiguratorRoute
    }
    '/$locale/admin/orderbekraftelse/$orderId': {
      id: '/$locale/admin/orderbekraftelse/$orderId'
      path: '/orderbekraftelse/$orderId'
      fullPath: '/$locale/admin/orderbekraftelse/$orderId'
      preLoaderRoute: typeof LocaleAdminOrderbekraftelseOrderIdRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/offert/$rfqId': {
      id: '/$locale/admin/offert/$rfqId'
      path: '/offert/$rfqId'
      fullPath: '/$locale/admin/offert/$rfqId'
      preLoaderRoute: typeof LocaleAdminOffertRfqIdRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
  }
}

interface LocaleAdminRouteChildren {
  LocaleAdminAuditRoute: typeof LocaleAdminAuditRoute
  LocaleAdminClaimsRoute: typeof LocaleAdminClaimsRoute
  LocaleAdminCrmRoute: typeof LocaleAdminCrmRoute
  LocaleAdminDashboardRoute: typeof LocaleAdminDashboardRoute
  LocaleAdminEkonomiRoute: typeof LocaleAdminEkonomiRoute
  LocaleAdminImagesRoute: typeof LocaleAdminImagesRoute
  LocaleAdminImportRoute: typeof LocaleAdminImportRoute
  LocaleAdminIntegrationsRoute: typeof LocaleAdminIntegrationsRoute
  LocaleAdminKnowledgeRoute: typeof LocaleAdminKnowledgeRoute
  LocaleAdminOrdersRoute: typeof LocaleAdminOrdersRoute
  LocaleAdminPricingRoute: typeof LocaleAdminPricingRoute
  LocaleAdminProductsRoute: typeof LocaleAdminProductsRoute
  LocaleAdminRfqRoute: typeof LocaleAdminRfqRoute
  LocaleAdminSettingsRoute: typeof LocaleAdminSettingsRoute
  LocaleAdminOffertRfqIdRoute: typeof LocaleAdminOffertRfqIdRoute
  LocaleAdminOrderbekraftelseOrderIdRoute: typeof LocaleAdminOrderbekraftelseOrderIdRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminAuditRoute: LocaleAdminAuditRoute,
  LocaleAdminClaimsRoute: LocaleAdminClaimsRoute,
  LocaleAdminCrmRoute: LocaleAdminCrmRoute,
  LocaleAdminDashboardRoute: LocaleAdminDashboardRoute,
  LocaleAdminEkonomiRoute: LocaleAdminEkonomiRoute,
  LocaleAdminImagesRoute: LocaleAdminImagesRoute,
  LocaleAdminImportRoute: LocaleAdminImportRoute,
  LocaleAdminIntegrationsRoute: LocaleAdminIntegrationsRoute,
  LocaleAdminKnowledgeRoute: LocaleAdminKnowledgeRoute,
  LocaleAdminOrdersRoute: LocaleAdminOrdersRoute,
  LocaleAdminPricingRoute: LocaleAdminPricingRoute,
  LocaleAdminProductsRoute: LocaleAdminProductsRoute,
  LocaleAdminRfqRoute: LocaleAdminRfqRoute,
  LocaleAdminSettingsRoute: LocaleAdminSettingsRoute,
  LocaleAdminOffertRfqIdRoute: LocaleAdminOffertRfqIdRoute,
  LocaleAdminOrderbekraftelseOrderIdRoute:
    LocaleAdminOrderbekraftelseOrderIdRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleConfiguratorRouteChildren {
  LocaleConfiguratorFamilyRoute: typeof LocaleConfiguratorFamilyRoute
  LocaleConfiguratorIndexRoute: typeof LocaleConfiguratorIndexRoute
  LocaleConfiguratorSchemaSchemaIdRoute: typeof LocaleConfiguratorSchemaSchemaIdRoute
}

const LocaleConfiguratorRouteChildren: LocaleConfiguratorRouteChildren = {
  LocaleConfiguratorFamilyRoute: LocaleConfiguratorFamilyRoute,
  LocaleConfiguratorIndexRoute: LocaleConfiguratorIndexRoute,
  LocaleConfiguratorSchemaSchemaIdRoute: LocaleConfiguratorSchemaSchemaIdRoute,
}

const LocaleConfiguratorRouteWithChildren =
  LocaleConfiguratorRoute._addFileChildren(LocaleConfiguratorRouteChildren)

interface LocaleGuiderRouteChildren {
  LocaleGuiderSlugRoute: typeof LocaleGuiderSlugRoute
  LocaleGuiderIndexRoute: typeof LocaleGuiderIndexRoute
}

const LocaleGuiderRouteChildren: LocaleGuiderRouteChildren = {
  LocaleGuiderSlugRoute: LocaleGuiderSlugRoute,
  LocaleGuiderIndexRoute: LocaleGuiderIndexRoute,
}

const LocaleGuiderRouteWithChildren = LocaleGuiderRoute._addFileChildren(
  LocaleGuiderRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleAdvisorRoute: typeof LocaleAdvisorRoute
  LocaleAppRoute: typeof LocaleAppRoute
  LocaleAssembliesRoute: typeof LocaleAssembliesRoute
  LocaleChatRoute: typeof LocaleChatRoute
  LocaleClaimsRoute: typeof LocaleClaimsRoute
  LocaleCompareRoute: typeof LocaleCompareRoute
  LocaleComponentsRoute: typeof LocaleComponentsRoute
  LocaleConfiguratorRoute: typeof LocaleConfiguratorRouteWithChildren
  LocaleConfigureRoute: typeof LocaleConfigureRoute
  LocaleConvertRoute: typeof LocaleConvertRoute
  LocaleGuiderRoute: typeof LocaleGuiderRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleMachineBuilderRoute: typeof LocaleMachineBuilderRoute
  LocaleNewRoute: typeof LocaleNewRoute
  LocaleOrdersRoute: typeof LocaleOrdersRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleProductsRoute: typeof LocaleProductsRoute
  LocaleProfileRoute: typeof LocaleProfileRoute
  LocaleProjectRoute: typeof LocaleProjectRoute
  LocaleProjectsRoute: typeof LocaleProjectsRoute
  LocaleSettingsRoute: typeof LocaleSettingsRoute
  LocaleShoppingListRoute: typeof LocaleShoppingListRoute
  LocaleSignupRoute: typeof LocaleSignupRoute
  LocaleTalkRoute: typeof LocaleTalkRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleWizardRoute: typeof LocaleWizardRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAssemblySlugRoute: typeof LocaleAssemblySlugRoute
  LocaleBomBomIdRoute: typeof LocaleBomBomIdRoute
  LocaleOcOrderIdRoute: typeof LocaleOcOrderIdRoute
  LocaleOffertRfqIdRoute: typeof LocaleOffertRfqIdRoute
  LocaleProductSkuRoute: typeof LocaleProductSkuRoute
  LocaleRfqRfqIdRoute: typeof LocaleRfqRfqIdRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleAdvisorRoute: LocaleAdvisorRoute,
  LocaleAppRoute: LocaleAppRoute,
  LocaleAssembliesRoute: LocaleAssembliesRoute,
  LocaleChatRoute: LocaleChatRoute,
  LocaleClaimsRoute: LocaleClaimsRoute,
  LocaleCompareRoute: LocaleCompareRoute,
  LocaleComponentsRoute: LocaleComponentsRoute,
  LocaleConfiguratorRoute: LocaleConfiguratorRouteWithChildren,
  LocaleConfigureRoute: LocaleConfigureRoute,
  LocaleConvertRoute: LocaleConvertRoute,
  LocaleGuiderRoute: LocaleGuiderRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleMachineBuilderRoute: LocaleMachineBuilderRoute,
  LocaleNewRoute: LocaleNewRoute,
  LocaleOrdersRoute: LocaleOrdersRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleProductsRoute: LocaleProductsRoute,
  LocaleProfileRoute: LocaleProfileRoute,
  LocaleProjectRoute: LocaleProjectRoute,
  LocaleProjectsRoute: LocaleProjectsRoute,
  LocaleSettingsRoute: LocaleSettingsRoute,
  LocaleShoppingListRoute: LocaleShoppingListRoute,
  LocaleSignupRoute: LocaleSignupRoute,
  LocaleTalkRoute: LocaleTalkRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleWizardRoute: LocaleWizardRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAssemblySlugRoute: LocaleAssemblySlugRoute,
  LocaleBomBomIdRoute: LocaleBomBomIdRoute,
  LocaleOcOrderIdRoute: LocaleOcOrderIdRoute,
  LocaleOffertRfqIdRoute: LocaleOffertRfqIdRoute,
  LocaleProductSkuRoute: LocaleProductSkuRoute,
  LocaleRfqRfqIdRoute: LocaleRfqRfqIdRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicNotifyRfqRoute: ApiPublicNotifyRfqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
