-- ============================================================
-- Tillbehörskatalog — ventiler, kopplingar, sensorer, FRL m.m.
-- ============================================================

-- 1. Nya kategorier
insert into public.categories(slug,name,description) values
  ('valve',         'Styrventil',          'Magnetventiler, riktningsventiler 5/2, 3/2'),
  ('valve-terminal','Ventilterminal',       'Ventilterminaler och manifolds'),
  ('frl',           'FRL-enhet',            'Filter, regulator, smörjare och kombinationer'),
  ('fitting',       'Koppling/Anslutning',  'Push-in kopplingar, snabbanslutningar, T- och L-kopplingar'),
  ('sensor',        'Sensor/Givare',        'Ändlägesgivare, Reed-kontakter, närhetsgivare för cylinder'),
  ('silencer',      'Ljuddämpare',          'Avgasljuddämpare för ventiler och cylindrar'),
  ('flow-control',  'Flödesreglering',      'Hastighetsstyrventiler, strypventiler'),
  ('tubing',        'Slang/Rör',            'Pneumatikslang, PU-slang, polyuretanslang'),
  ('mounting',      'Fäste/Montering',      'Cylinderfästen, gaffelkopplingar, pivåfästen, adaptrar'),
  ('cable',         'Kabel/Kontakt',        'Sensorkablar, M8/M12-kontakter, förlängningskablar')
on conflict (slug) do nothing;

-- 2. Nya varumärken (om saknas)
insert into public.brands(slug,name,country) values
  ('norgren',    'Norgren',    'GB'),
  ('metal-work', 'Metal Work', 'IT'),
  ('camozzi',    'Camozzi',    'IT')
on conflict (slug) do nothing;

-- 3. Produkter (~82 st)
with b as (select slug,id from public.brands),
     c as (select slug,id from public.categories)
insert into public.products(sku,brand_id,category_id,family,name,description,purchase_price,lead_time_days,availability)
select * from (values
  ('FE-VUVG-L10-M52-MT-M5',(select id from b where slug='festo'),(select id from c where slug='valve'),'VUVG','VUVG-L10 5/2 monostabil M5','Magnetventil 5/2 monostabil, M5-anslutning, 24VDC',695,7,'stock'),
  ('FE-VUVG-L14-B52-T-G18',(select id from b where slug='festo'),(select id from c where slug='valve'),'VUVG','VUVG-L14 5/2 bistabil G1/8','Magnetventil 5/2 bistabil, G1/8-anslutning, 24VDC',1150,7,'stock'),
  ('FE-MFH-5-1-8',(select id from b where slug='festo'),(select id from c where slug='valve'),'MFH','MFH-5/2-D-1-S G1/8','5/2-magnetventil standard, G1/8, 24VDC',580,5,'stock'),
  ('FE-VUVG-L10-P53C-T-M5',(select id from b where slug='festo'),(select id from c where slug='valve'),'VUVG','VUVG-L10 5/3 mittutluft M5','Magnetventil 5/3 mittutluft, M5, 24VDC',890,10,'stock'),
  ('FE-VZWE-1-M22C-G18-135',(select id from b where slug='festo'),(select id from c where slug='valve'),'VZWE','VZWE-1 2/2-ventil G1/8','2/2 stängd normalläge, G1/8, 24VDC',420,14,'stock'),
  ('SMC-VQ1101N-5G',(select id from b where slug='smc'),(select id from c where slug='valve'),'VQ1000','VQ1101N 5/2 monostabil G1/8','5/2 magnetventil, G1/8, 24VDC, direkt styrd',680,5,'stock'),
  ('SMC-SY3120-5LOZ',(select id from b where slug='smc'),(select id from c where slug='valve'),'SY3000','SY3120 5/2 monostabil G1/8','5/2 magnetventil sub-bas, G1/8, 24VDC',850,7,'stock'),
  ('SMC-VF3130-5G-02',(select id from b where slug='smc'),(select id from c where slug='valve'),'VF3000','VF3130 5/2 bistabil G1/4','5/2 bistabil magnetventil, G1/4, 24VDC',920,10,'stock'),
  ('FE-VTSA-FC-4-1-DN-G18',(select id from b where slug='festo'),(select id from c where slug='valve-terminal'),'VTSA','VTSA 4-stations G1/8','Ventilterminal 4 stationer, G1/8, utan ventiler',3200,14,'order'),
  ('FE-VTSA-FC-8-1-DN-G18',(select id from b where slug='festo'),(select id from c where slug='valve-terminal'),'VTSA','VTSA 8-stations G1/8','Ventilterminal 8 stationer, G1/8, utan ventiler',5800,14,'order'),
  ('FE-VTUG-10-5-M32-S',(select id from b where slug='festo'),(select id from c where slug='valve-terminal'),'VTUG','VTUG-10 4-stations med EtherNet/IP','Ventilterminal 10mm, 4 stationer, EtherNet/IP',7500,21,'order'),
  ('FE-MPA-S-EX1-8',(select id from b where slug='festo'),(select id from c where slug='valve-terminal'),'MPA','MPA-S 8-stations IO-Link','Ventilterminal MPA-S, 8 ventilplatser, IO-Link',9200,21,'order'),
  ('SMC-EX500-Q011',(select id from b where slug='smc'),(select id from c where slug='valve-terminal'),'EX500','EX500 4-stations EtherNet/IP','Ventilterminal EX500, 4 stationer, EtherNet/IP',4800,14,'order'),
  ('SMC-SS5V1-W10S1-04',(select id from b where slug='smc'),(select id from c where slug='valve-terminal'),'SV1000','SV1000 4-stations terminal','SV1000 ventilterminal, 4 stationer, G1/8',3500,14,'order'),
  ('FE-MS4-LFR-14-D6',(select id from b where slug='festo'),(select id from c where slug='frl'),'MS','MS4 Filter+Regulator G1/4','Kombinationsenhet filter+regulator, G1/4, 0.5-10 bar',820,5,'stock'),
  ('FE-MS6-LFR-14-D7',(select id from b where slug='festo'),(select id from c where slug='frl'),'MS','MS6 Filter+Regulator G1/4','Kombinationsenhet filter+regulator stor, G1/4, 0.5-12 bar',1150,7,'stock'),
  ('FE-MS4-LF-14-CRG',(select id from b where slug='festo'),(select id from c where slug='frl'),'MS','MS4 Filter G1/4','Luftfilter 40µm, G1/4, med manuell kondensatavtappning',420,5,'stock'),
  ('FE-MS4-LR-14-D7',(select id from b where slug='festo'),(select id from c where slug='frl'),'MS','MS4 Regulator G1/4','Tryckregulatorer G1/4, 0.5-10 bar, med manometer',380,5,'stock'),
  ('FE-MS4-LFR-14-D6-AS',(select id from b where slug='festo'),(select id from c where slug='frl'),'MS','MS4 FRL-kombienhet G1/4','Filter+Regulator+Smörjare, G1/4',1250,7,'stock'),
  ('SMC-AC20A-02G',(select id from b where slug='smc'),(select id from c where slug='frl'),'AC','AC20A Filter+Regulator G1/4','Kombinationsenhet AC20A, G1/4, 0.05-0.85 MPa',650,5,'stock'),
  ('SMC-AC30A-03G',(select id from b where slug='smc'),(select id from c where slug='frl'),'AC','AC30A Filter+Regulator G3/8','Kombinationsenhet AC30A, G3/8, 0.05-0.85 MPa',890,5,'stock'),
  ('SMC-AW20-02G',(select id from b where slug='smc'),(select id from c where slug='frl'),'AW','AW20 Filter+Regulator G1/4','Filterregulator AW20, G1/4, med vattenavtappning',480,5,'stock'),
  ('FE-QS-M5-4',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QS-M5-4 push-in M5 Ø4','Rak push-in koppling M5 × 4mm, PA',42,3,'stock'),
  ('FE-QS-G18-6',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QS-G1/8-6 push-in G1/8 Ø6','Rak push-in koppling G1/8 × 6mm, PA',48,3,'stock'),
  ('FE-QS-G14-8',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QS-G1/4-8 push-in G1/4 Ø8','Rak push-in koppling G1/4 × 8mm, PA',55,3,'stock'),
  ('FE-QS-G14-10',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QS-G1/4-10 push-in G1/4 Ø10','Rak push-in koppling G1/4 × 10mm, PA',62,3,'stock'),
  ('FE-QSL-G18-6',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QSL-G1/8-6 L-koppling G1/8 Ø6','Vinkelkoppling 90° G1/8 × 6mm',68,3,'stock'),
  ('FE-QSL-G14-8',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QSL-G1/4-8 L-koppling G1/4 Ø8','Vinkelkoppling 90° G1/4 × 8mm',78,3,'stock'),
  ('FE-QST-6',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QST-6 T-koppling Ø6','T-koppling 3-vägs push-in, 6mm, PA',85,3,'stock'),
  ('FE-QST-8',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QST-8 T-koppling Ø8','T-koppling 3-vägs push-in, 8mm, PA',95,3,'stock'),
  ('FE-QSY-6',(select id from b where slug='festo'),(select id from c where slug='fitting'),'QS','QSY-6 Y-koppling Ø6','Y-koppling push-in 6mm',88,3,'stock'),
  ('SMC-KQ2H04-M5A',(select id from b where slug='smc'),(select id from c where slug='fitting'),'KQ2','KQ2H04-M5A rak M5 Ø4','Rak push-in M5 × 4mm',38,3,'stock'),
  ('SMC-KQ2H06-01S',(select id from b where slug='smc'),(select id from c where slug='fitting'),'KQ2','KQ2H06-01S rak G1/8 Ø6','Rak push-in G1/8 × 6mm',45,3,'stock'),
  ('SMC-KQ2H08-02S',(select id from b where slug='smc'),(select id from c where slug='fitting'),'KQ2','KQ2H08-02S rak G1/4 Ø8','Rak push-in G1/4 × 8mm',52,3,'stock'),
  ('SMC-KQ2L06-01S',(select id from b where slug='smc'),(select id from c where slug='fitting'),'KQ2','KQ2L06-01S L-koppling G1/8 Ø6','L-koppling 90° G1/8 × 6mm',65,3,'stock'),
  ('SMC-KQ2T06-00',(select id from b where slug='smc'),(select id from c where slug='fitting'),'KQ2','KQ2T06-00 T-koppling Ø6','T-koppling push-in 6mm',80,3,'stock'),
  ('FE-SMT-8M-A-PS-24V-E-0.3-M8D',(select id from b where slug='festo'),(select id from c where slug='sensor'),'SMT','SMT-8M proximity T-spår 24V M8','Ändlägesgivare för T-spår, PNP, 24V, M8-kontakt',245,5,'stock'),
  ('FE-SMT-10-PS-24V-E-0.3-M8D',(select id from b where slug='festo'),(select id from c where slug='sensor'),'SMT','SMT-10 proximity T-spår 24V M8','Ändlägesgivare Ø10-spår, PNP, 24V, M8-kontakt',265,5,'stock'),
  ('FE-SIES-8M-DS-24V',(select id from b where slug='festo'),(select id from c where slug='sensor'),'SIES','SIES-8M Reed T-spår 2-ledare','Reed-kontakt T-spår 8mm, 2-ledare, 24V, 2.5m',185,5,'stock'),
  ('FE-SIET-8M-DS-24V',(select id from b where slug='festo'),(select id from c where slug='sensor'),'SIET','SIET-8M Reed T-spår med LED','Reed-kontakt T-spår 8mm, LED-indikering, 24V, 2.5m',215,5,'stock'),
  ('FE-SME-8M-DS-24V-K-2.5-M8D',(select id from b where slug='festo'),(select id from c where slug='sensor'),'SME','SME-8M Reed T-spår M8-kontakt','Reed-kontakt 8mm-spår, M8-kontakt, 24V',235,5,'stock'),
  ('SMC-D-A73',(select id from b where slug='smc'),(select id from c where slug='sensor'),'D-A','D-A73 Reed T-spår 24V','Reed-kontakt för T-spår, 24V, 2-ledare, kabel 3m',195,5,'stock'),
  ('SMC-D-A93',(select id from b where slug='smc'),(select id from c where slug='sensor'),'D-A','D-A93 solid state T-spår PNP','Solid state givare T-spår, PNP 24V, kabel 3m',280,5,'stock'),
  ('SMC-D-M9B',(select id from b where slug='smc'),(select id from c where slug='sensor'),'D-M9','D-M9B band-sensor PNP 24V','Bandfästad givare, PNP, 24V, LED, M8-kontakt',320,7,'stock'),
  ('SMC-D-A72H',(select id from b where slug='smc'),(select id from c where slug='sensor'),'D-A','D-A72H Reed C-spår 24V','Reed-kontakt för C-spår, 24V, kabel 3m',185,5,'stock'),
  ('FE-U-1-8',(select id from b where slug='festo'),(select id from c where slug='silencer'),'U','U-1/8 ljuddämpare G1/8','Sintermetall ljuddämpare, G1/8-gänga',38,3,'stock'),
  ('FE-U-1-4',(select id from b where slug='festo'),(select id from c where slug='silencer'),'U','U-1/4 ljuddämpare G1/4','Sintermetall ljuddämpare, G1/4-gänga',48,3,'stock'),
  ('FE-U-M5',(select id from b where slug='festo'),(select id from c where slug='silencer'),'U','U-M5 ljuddämpare M5','Sintermetall ljuddämpare, M5-gänga',32,3,'stock'),
  ('SMC-AN10-01',(select id from b where slug='smc'),(select id from c where slug='silencer'),'AN','AN10-01 ljuddämpare G1/8','Sintermetall ljuddämpare G1/8',32,3,'stock'),
  ('SMC-AN20-02',(select id from b where slug='smc'),(select id from c where slug='silencer'),'AN','AN20-02 ljuddämpare G1/4','Sintermetall ljuddämpare G1/4',42,3,'stock'),
  ('SMC-AN30-03',(select id from b where slug='smc'),(select id from c where slug='silencer'),'AN','AN30-03 ljuddämpare G3/8','Sintermetall ljuddämpare G3/8',55,3,'stock'),
  ('FE-GRLA-18-QS-6-D',(select id from b where slug='festo'),(select id from c where slug='flow-control'),'GRLA','GRLA-1/8-QS-6 avgasstrypare','Avgashastighetsstyrventil G1/8 × 6mm push-in',95,5,'stock'),
  ('FE-GRLA-14-QS-8-D',(select id from b where slug='festo'),(select id from c where slug='flow-control'),'GRLA','GRLA-1/4-QS-8 avgasstrypare','Avgashastighetsstyrventil G1/4 × 8mm push-in',115,5,'stock'),
  ('FE-GRLZ-18-QS-6-D',(select id from b where slug='festo'),(select id from c where slug='flow-control'),'GRLZ','GRLZ-1/8-QS-6 tilloppsreglering','Tilloppsstyrventil G1/8 × 6mm push-in',95,5,'stock'),
  ('FE-VFOE-18-T',(select id from b where slug='festo'),(select id from c where slug='flow-control'),'VFOE','VFOE-1/8 snabbutluft','Snabbutluftsventil G1/8, för snabb cylinderrörelse',145,5,'stock'),
  ('SMC-AS1201F-M5-04',(select id from b where slug='smc'),(select id from c where slug='flow-control'),'AS','AS1201F-M5-04 strypkoppling M5','Strypkoppling M5 × 4mm, avgasstyrning',82,3,'stock'),
  ('SMC-AS2201F-01-06A',(select id from b where slug='smc'),(select id from c where slug='flow-control'),'AS','AS2201F-01-06A strypkoppling G1/8','Strypkoppling G1/8 × 6mm, avgasstyrning',105,3,'stock'),
  ('SMC-AS3201F-02-08A',(select id from b where slug='smc'),(select id from c where slug='flow-control'),'AS','AS3201F-02-08A strypkoppling G1/4','Strypkoppling G1/4 × 8mm, avgasstyrning',125,3,'stock'),
  ('SMC-VHS20-02A',(select id from b where slug='smc'),(select id from c where slug='flow-control'),'VHS','VHS20-02A manuell säkerhetsventil G1/4','Manuell säkerhetsventil för tryckluft, G1/4',580,7,'stock'),
  ('FE-PAN-V0-4X0.75-BL-50',(select id from b where slug='festo'),(select id from c where slug='tubing'),'PAN','PAN Ø4mm blå PU-slang 50m','Polyuretanslang 4×0.75mm blå, rulle 50m, flamsäker',520,5,'stock'),
  ('FE-PAN-V0-6X1-BL-50',(select id from b where slug='festo'),(select id from c where slug='tubing'),'PAN','PAN Ø6mm blå PU-slang 50m','Polyuretanslang 6×1mm blå, rulle 50m, flamsäker',680,5,'stock'),
  ('FE-PAN-V0-8X1.25-BL-50',(select id from b where slug='festo'),(select id from c where slug='tubing'),'PAN','PAN Ø8mm blå PU-slang 50m','Polyuretanslang 8×1.25mm blå, rulle 50m, flamsäker',850,5,'stock'),
  ('FE-PAN-V0-10X1.5-BL-50',(select id from b where slug='festo'),(select id from c where slug='tubing'),'PAN','PAN Ø10mm blå PU-slang 50m','Polyuretanslang 10×1.5mm blå, rulle 50m, flamsäker',1050,5,'stock'),
  ('FE-PAN-V0-6X1-SW-50',(select id from b where slug='festo'),(select id from c where slug='tubing'),'PAN','PAN Ø6mm svart PU-slang 50m','Polyuretanslang 6×1mm svart UV-beständig, 50m',720,5,'stock'),
  ('SMC-TU0425BU-20',(select id from b where slug='smc'),(select id from c where slug='tubing'),'TU','TU Ø4mm blå PU-slang 20m','PU-slang 4×2.5mm blå, rulle 20m',195,3,'stock'),
  ('SMC-TU0604BU-20',(select id from b where slug='smc'),(select id from c where slug='tubing'),'TU','TU Ø6mm blå PU-slang 20m','PU-slang 6×4mm blå, rulle 20m',245,3,'stock'),
  ('SMC-TU0805BU-20',(select id from b where slug='smc'),(select id from c where slug='tubing'),'TU','TU Ø8mm blå PU-slang 20m','PU-slang 8×5mm blå, rulle 20m',310,3,'stock'),
  ('FE-HNC-32',(select id from b where slug='festo'),(select id from c where slug='mounting'),'HNC','HNC-32 gaffelkoppling Ø32','Gaffelkoppling för DSBC/DNC Ø32, stål förzinkat',185,5,'stock'),
  ('FE-HNC-40',(select id from b where slug='festo'),(select id from c where slug='mounting'),'HNC','HNC-40 gaffelkoppling Ø40','Gaffelkoppling för DSBC/DNC Ø40, stål förzinkat',210,5,'stock'),
  ('FE-HNC-50',(select id from b where slug='festo'),(select id from c where slug='mounting'),'HNC','HNC-50 gaffelkoppling Ø50','Gaffelkoppling för DSBC/DNC Ø50, stål förzinkat',245,5,'stock'),
  ('FE-HNC-63',(select id from b where slug='festo'),(select id from c where slug='mounting'),'HNC','HNC-63 gaffelkoppling Ø63','Gaffelkoppling för DSBC/DNC Ø63, stål förzinkat',285,5,'stock'),
  ('FE-SNCS-32',(select id from b where slug='festo'),(select id from c where slug='mounting'),'SNCS','SNCS-32 svängfläns Ø32','Svängfläns/pivåfäste för DSBC Ø32',195,5,'stock'),
  ('FE-SNCS-40',(select id from b where slug='festo'),(select id from c where slug='mounting'),'SNCS','SNCS-40 svängfläns Ø40','Svängfläns/pivåfäste för DSBC Ø40',225,5,'stock'),
  ('FE-SNCS-50',(select id from b where slug='festo'),(select id from c where slug='mounting'),'SNCS','SNCS-50 svängfläns Ø50','Svängfläns/pivåfäste för DSBC Ø50',265,5,'stock'),
  ('FE-FNC-32',(select id from b where slug='festo'),(select id from c where slug='mounting'),'FNC','FNC-32 fotfäste Ø32','Fotfäste (LB) för DSBC Ø32',145,5,'stock'),
  ('FE-FNC-50',(select id from b where slug='festo'),(select id from c where slug='mounting'),'FNC','FNC-50 fotfäste Ø50','Fotfäste (LB) för DSBC Ø50',175,5,'stock'),
  ('FE-CRHN-32',(select id from b where slug='festo'),(select id from c where slug='mounting'),'CRHN','CRHN-32 swivel-flanskfäste Ø32','Swivel-flanskfäste för roterande fäste Ø32',320,7,'stock'),
  ('SMC-CA2-Z32-CS16',(select id from b where slug='smc'),(select id from c where slug='mounting'),'CS16','CS16-32 gaffelkoppling Ø32','Gaffelkoppling CA2-serien Ø32',175,5,'stock'),
  ('SMC-CA2-Z50-CS16',(select id from b where slug='smc'),(select id from c where slug='mounting'),'CS16','CS16-50 gaffelkoppling Ø50','Gaffelkoppling CA2-serien Ø50',235,5,'stock'),
  ('SMC-CDS1-LA32',(select id from b where slug='smc'),(select id from c where slug='mounting'),'LA','LA-32 fotfäste Ø32','Fotfäste för C85/CDS1 Ø32',140,5,'stock'),
  ('FE-NEBU-M8G3-K-2-N-M8G3',(select id from b where slug='festo'),(select id from c where slug='cable'),'NEBU','NEBU M8 3-pol 2m kabel','Anslutningskabel M8 3-polig rak-rak, 2m, PVC',155,3,'stock'),
  ('FE-NEBU-M8G3-K-5-N-M8G3',(select id from b where slug='festo'),(select id from c where slug='cable'),'NEBU','NEBU M8 3-pol 5m kabel','Anslutningskabel M8 3-polig rak-rak, 5m, PVC',210,3,'stock'),
  ('FE-NEBU-M12G5-K-2-N-M12G5',(select id from b where slug='festo'),(select id from c where slug='cable'),'NEBU','NEBU M12 5-pol 2m kabel','Anslutningskabel M12 5-polig rak-rak, 2m, PVC',185,3,'stock'),
  ('SMC-E2-M8-2',(select id from b where slug='smc'),(select id from c where slug='cable'),'E2','SMC E2 M8 2m sensorkabel','M8 3-pol sensorkabel, 2m, PNP/NPN kompatibel',145,3,'stock'),
  ('FE-SPAU-P10R-H-G18-L-PNLK',(select id from b where slug='festo'),(select id from c where slug='sensor'),'SPAU','SPAU tryckvakt G1/8 PNP','Digital tryckvakt G1/8, PNP, display, 0-10 bar',650,7,'stock'),
  ('SMC-ZSE10-01-15',(select id from b where slug='smc'),(select id from c where slug='sensor'),'ZSE','ZSE10 tryckvakt G1/8 PNP','Digital tryckvakt ZSE10, G1/8, PNP, 2-färg display',580,5,'stock'),
  ('FE-VADMI-95-AP',(select id from b where slug='festo'),(select id from c where slug='valve'),'VADMI','VADMI-95 vakumejektor M5','Vakumejektor med M5 lufttillförsel, 95 mbar',820,7,'stock'),
  ('SMC-ZH05DS-06-06-06',(select id from b where slug='smc'),(select id from c where slug='valve'),'ZH','ZH05DS vakumejektor Ø6','Vakumejektor ZH05DS, 6mm anslutning, -88 kPa',695,7,'stock'),
  ('FE-LR-14-D-MINI',(select id from b where slug='festo'),(select id from c where slug='frl'),'LR','LR-1/4-D-MINI tryckreduceringventil','Miniatyrtryckreducerare G1/4, 0.1-6 bar, utan manometer',285,5,'stock'),
  ('SMC-AR20-02G',(select id from b where slug='smc'),(select id from c where slug='frl'),'AR','AR20-02G tryckreduceringventil G1/4','Tryckregulatorer AR20, G1/4, med manometerutgång',265,5,'stock')
) as t(sku,brand_id,category_id,family,name,description,purchase_price,lead_time_days,availability)
on conflict (sku) do nothing;
